<Project Sdk="Dalamud.NET.Sdk/15.0.0">
    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <!-- Windows-specific target framework -->
        <Version>2.1.0.11</Version>
        <Description>Instant Character Switching Made Simple. Create and save character profiles, then switch between them instantly. Applies Penumbra Collections, Glamourer Designs, Customize+ Profiles, Honorifics, Moodles, and Idles. Perfect for roleplayers, gposers, and anyone who loves seamless character customization.</Description>
        <PackageProjectUrl>https://github.com/USBTURTLECUP/Character-Select-</PackageProjectUrl>
        <PackageLicenseExpression>AGPL-3.0-or-later</PackageLicenseExpression>
        <IsPackable>false</IsPackable>
        <UseWindowsForms>true</UseWindowsForms>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
      <UserSecretsId>39e1f8a5-b0d6-44c6-ad05-a9405ac1dcfb</UserSecretsId>
  </PropertyGroup>
    <ItemGroup>
        <Reference Include="System.Windows.Forms" />
    </ItemGroup>
    <ItemGroup>
        <Content Include="CharacterSelectPlugin.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>

        <Content Include="Assets\**\*.*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>